### ISSUE TITLE
package naming

### ISSUE THREAD

**Issue by algent-al** [emaimx/Solus-ROCm-build#9]
Package naming are different upstream, probably we should follow that.
- `roct-thunk-interface` could be named as `libhsakmt`.
- `rocm-runtime` could be named as `hsakmt`. See [here](https://repology.org/project/hsakmt/packages).

Fedora for example doesn't use at all `roct-thunk-interface`, but it merges it with `hsakmt` (`rocm-runtime`). See [here](https://src.fedoraproject.org/rpms/hsakmt/blob/master/f/hsakmt.spec).

**Comment by Tzigamm** [comment]
Why are they using this name? Maybe it's a legacy name, as the official name seems to be ROCT-Thunk-Interface ([from their github page](https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface))

**Comment by algent-al** [comment]
I think because those packages have libhsakmt libraries.

**Comment by algent-al** [comment]
You should see list of files on pspec_x86_64.xml file.

**Comment by algent-al** [comment]
https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/blob/master/DEBIAN/control

**Comment by algent-al** [comment]
ROCm is now available in Solus Repos.
